//
//  Persistence.swift
//  DW Episode Guide
//
//  Created by Mark Howard on 07/11/2021.
//

import CoreData

struct PersistenceController {
    static let shared = PersistenceController()

    static var preview: PersistenceController = {
        let result = PersistenceController(inMemory: true)
        let viewContext = result.container.viewContext
        /*for _ in 0..<10 {
            let newItem = ProgrammingLanguage(context: viewContext)
            newItem.name = "Test"
        }*/
        
        //Classic Series 1
            let anunearthlychild = AnUnearthlyChildClass(context: viewContext)
            anunearthlychild.title = "An Unearthly Child"
        anunearthlychild.broadcast = "23 November 1963\n14 December 1963"
        anunearthlychild.companions = "Susan Foreman (Carole Ann Ford)\nIan Chesterton (William Russell)\nBarbara Wright (Jacqueline Hill)"
        anunearthlychild.director = "Waris Hussein"
        anunearthlychild.doctor = "1st Doctor\n(William Hartnell)"
        anunearthlychild.length = "4 Episodes\n25 Minutes Each"
        anunearthlychild.producer = "Verity Lambert\nMervyn Pinfield"
        let thedaleks = TheDaleksClass(context: viewContext)
        thedaleks.title = "The Daleks"
        thedaleks.broadcast = "21 December 1963\n1 February 1964"
        thedaleks.companions = "Susan Foreman (Carole Ann Ford)\nIan Chesterton (William Russell)\nBarbara Wright (Jacqueline Hill)"
        thedaleks.director = "Christopher Barry\nRichard Martin"
        thedaleks.doctor = "1st Doctor\n(William Hartnell)"
        thedaleks.length = "7 Episodes\n25 Minutes Each"
        thedaleks.producer = "Verity Lambert\nMervyn Pinfield"
        let theedgeofdestruction = TheEdgeOfDestructionClass(context: viewContext)
        theedgeofdestruction.title = "The Edge Of Destruction"
        theedgeofdestruction.broadcast = ""
        theedgeofdestruction.companions = ""
        theedgeofdestruction.director = ""
        theedgeofdestruction.doctor = ""
        theedgeofdestruction.length = ""
        theedgeofdestruction.producer = ""
        let marcopolo = MarcoPoloClass(context: viewContext)
        marcopolo.title = ""
        marcopolo.broadcast = ""
        marcopolo.companions = ""
        marcopolo.director = ""
        marcopolo.doctor = ""
        marcopolo.length = ""
        marcopolo.producer = ""
        let thekeysofmarinus = TheKeysOfMarinusClass(context: viewContext)
        thekeysofmarinus.title = ""
        thekeysofmarinus.broadcast = ""
        thekeysofmarinus.companions = ""
        thekeysofmarinus.director = ""
        thekeysofmarinus.doctor = ""
        thekeysofmarinus.length = ""
        thekeysofmarinus.producer = ""
        let theaztecs = TheAztecsClass(context: viewContext)
        theaztecs.title = ""
        theaztecs.broadcast = ""
        theaztecs.companions = ""
        theaztecs.director = ""
        theaztecs.doctor = ""
        theaztecs.length = ""
        theaztecs.producer = ""
        let thesensorites = TheSensoritesClass(context: viewContext)
        thesensorites.title = ""
        thesensorites.broadcast = ""
        thesensorites.companions = ""
        thesensorites.director = ""
        thesensorites.doctor = ""
        thesensorites.length = ""
        thesensorites.producer = ""
        let thereignofterror = TheReignOfTerrorClass(context: viewContext)
        thereignofterror.title = ""
        thereignofterror.broadcast = ""
        thereignofterror.companions = ""
        thereignofterror.director = ""
        thereignofterror.doctor = ""
        thereignofterror.length = ""
        thereignofterror.producer = ""
        
        //Classic Series 2
        let planetofgiants = PlanetOfGiantsClass(context: viewContext)
        planetofgiants.title = ""
        planetofgiants.broadcast = ""
        planetofgiants.companions = ""
        planetofgiants.director = ""
        planetofgiants.doctor = ""
        planetofgiants.length = ""
        planetofgiants.producer = ""
        let thedalekinvasionofearth = TheDalekInvasionOfEarthClass(context: viewContext)
        thedalekinvasionofearth.title = ""
        thedalekinvasionofearth.broadcast = ""
        thedalekinvasionofearth.companions = ""
        thedalekinvasionofearth.director = ""
        thedalekinvasionofearth.doctor = ""
        thedalekinvasionofearth.length = ""
        thedalekinvasionofearth.producer = ""
        let therescue = TheRescueClass(context: viewContext)
        therescue.title = ""
        therescue.broadcast = ""
        therescue.companions = ""
        therescue.director = ""
        therescue.doctor = ""
        therescue.length = ""
        therescue.producer = ""
        let theromans = TheRomansClass(context: viewContext)
        theromans.title = ""
        theromans.broadcast = ""
        theromans.companions = ""
        theromans.director = ""
        theromans.doctor = ""
        theromans.length = ""
        theromans.producer = ""
        let thewebplanet = TheWebPlanetClass(context: viewContext)
        thewebplanet.title = ""
        thewebplanet.broadcast = ""
        thewebplanet.companions = ""
        thewebplanet.director = ""
        thewebplanet.doctor = ""
        thewebplanet.length = ""
        thewebplanet.producer = ""
        let thecrusade = TheCrusadeClass(context: viewContext)
        thecrusade.title = ""
        thecrusade.broadcast = ""
        thecrusade.companions = ""
        thecrusade.director = ""
        thecrusade.doctor = ""
        thecrusade.length = ""
        thecrusade.producer = ""
        let thespacemuseum = TheSpaceMuseumClass(context: viewContext)
        thespacemuseum.title = ""
        thespacemuseum.broadcast = ""
        thespacemuseum.companions = ""
        thespacemuseum.director = ""
        thespacemuseum.doctor = ""
        thespacemuseum.length = ""
        thespacemuseum.producer = ""
        let thechase = TheChaseClass(context: viewContext)
        thechase.title = ""
        thechase.broadcast = ""
        thechase.companions = ""
        thechase.director = ""
        thechase.doctor = ""
        thechase.length = ""
        thechase.producer = ""
        let thetimemeddler = TheTimeMeddlerClass(context: viewContext)
        thetimemeddler.title = ""
        thetimemeddler.broadcast = ""
        thetimemeddler.companions = ""
        thetimemeddler.director = ""
        thetimemeddler.doctor = ""
        thetimemeddler.length = ""
        thetimemeddler.producer = ""
        //Classic Series 3
        let galaxy4 = Galaxy4Class(context: viewContext)
        galaxy4.title = ""
        galaxy4.broadcast = ""
        galaxy4.companions = ""
        galaxy4.director = ""
        galaxy4.doctor = ""
        galaxy4.length = ""
        galaxy4.producer = ""
        let missiontotheunknown = MissionToTheUnknownClass(context: viewContext)
        missiontotheunknown.title = ""
        missiontotheunknown.broadcast = ""
        missiontotheunknown.companions = ""
        missiontotheunknown.director = ""
        missiontotheunknown.doctor = ""
        missiontotheunknown.length = ""
        missiontotheunknown.producer = ""
        let themythmakers = TheMythMakersClass(context: viewContext)
        themythmakers.title = ""
        themythmakers.broadcast = ""
        themythmakers.companions = ""
        themythmakers.director = ""
        themythmakers.doctor = ""
        themythmakers.length = ""
        themythmakers.producer = ""
        let thedaleksmasterplan = TheDaleksMasterPlanClass(context: viewContext)
        thedaleksmasterplan.title = ""
        thedaleksmasterplan.broadcast = ""
        thedaleksmasterplan.companions = ""
        thedaleksmasterplan.director = ""
        thedaleksmasterplan.doctor = ""
        thedaleksmasterplan.length = ""
        thedaleksmasterplan.producer = ""
        let themassacre = TheMassacreClass(context: viewContext)
        themassacre.title = ""
        themassacre.broadcast = ""
        themassacre.companions = ""
        themassacre.director = ""
        themassacre.doctor = ""
        themassacre.length = ""
        themassacre.producer = ""
        let theark = TheArkClass(context: viewContext)
        theark.title = ""
        theark.broadcast = ""
        theark.companions = ""
        theark.director = ""
        theark.doctor = ""
        theark.length = ""
        theark.producer = ""
        let thecelestialtoymaker = TheCelestialToymakerClass(context: viewContext)
        thecelestialtoymaker.title = ""
        thecelestialtoymaker.broadcast = ""
        thecelestialtoymaker.companions = ""
        thecelestialtoymaker.director = ""
        thecelestialtoymaker.doctor = ""
        thecelestialtoymaker.length = ""
        thecelestialtoymaker.producer = ""
        let thegunfighters = TheGunfightersClass(context: viewContext)
        thegunfighters.title = ""
        thegunfighters.broadcast = ""
        thegunfighters.companions = ""
        thegunfighters.director = ""
        thegunfighters.doctor = ""
        thegunfighters.length = ""
        thegunfighters.producer = ""
        let thesavages = TheSavagesClass(context: viewContext)
        thesavages.title = ""
        thesavages.broadcast = ""
        thesavages.companions = ""
        thesavages.director = ""
        thesavages.doctor = ""
        thesavages.length = ""
        thesavages.producer = ""
        let thewarmachines = TheWarMachinesClass(context: viewContext)
        thewarmachines.title = ""
        thewarmachines.broadcast = ""
        thewarmachines.companions = ""
        thewarmachines.director = ""
        thewarmachines.doctor = ""
        thewarmachines.length = ""
        thewarmachines.producer = ""
        //Classic Series 4
        let thesmugglers = TheSmugglersClass(context: viewContext)
        thesmugglers.title = ""
        thesmugglers.broadcast = ""
        thesmugglers.companions = ""
        thesmugglers.director = ""
        thesmugglers.doctor = ""
        thesmugglers.length = ""
        thesmugglers.producer = ""
        let thetenthplanet = TheTenthPlanetClass(context: viewContext)
        thetenthplanet.title = ""
        thetenthplanet.broadcast = ""
        thetenthplanet.companions = ""
        thetenthplanet.director = ""
        thetenthplanet.doctor = ""
        thetenthplanet.length = ""
        thetenthplanet.producer = ""
        let thepowerofthedaleks = ThePowerOfTheDaleksClass(context: viewContext)
        thepowerofthedaleks.title = ""
        thepowerofthedaleks.broadcast = ""
        thepowerofthedaleks.companions = ""
        thepowerofthedaleks.director = ""
        thepowerofthedaleks.doctor = ""
        thepowerofthedaleks.length = ""
        thepowerofthedaleks.producer = ""
        let thehighlanders = TheHighlandersClass(context: viewContext)
        thehighlanders.title = ""
        thehighlanders.broadcast = ""
        thehighlanders.companions = ""
        thehighlanders.director = ""
        thehighlanders.doctor = ""
        thehighlanders.length = ""
        thehighlanders.producer = ""
        let theunderwatermenace = TheUnderwaterMenaceClass(context: viewContext)
        theunderwatermenace.title = ""
        theunderwatermenace.broadcast = ""
        theunderwatermenace.companions = ""
        theunderwatermenace.director = ""
        theunderwatermenace.doctor = ""
        theunderwatermenace.length = ""
        theunderwatermenace.producer = ""
        let themoonbase = TheMoonbaseClass(context: viewContext)
        themoonbase.title = ""
        themoonbase.broadcast = ""
        themoonbase.companions = ""
        themoonbase.director = ""
        themoonbase.doctor = ""
        themoonbase.length = ""
        themoonbase.producer = ""
        let themacraterror = TheMacraTerrorClass(context: viewContext)
        themacraterror.title = ""
        themacraterror.broadcast = ""
        themacraterror.companions = ""
        themacraterror.director = ""
        themacraterror.doctor = ""
        themacraterror.length = ""
        themacraterror.producer = ""
        let thefacelessones = TheFacelessOnesClass(context: viewContext)
        thefacelessones.title = ""
        thefacelessones.broadcast = ""
        thefacelessones.companions = ""
        thefacelessones.director = ""
        thefacelessones.doctor = ""
        thefacelessones.length = ""
        thefacelessones.producer = ""
        let theevilofthedaleks = TheEvilOfTheDaleksClass(context: viewContext)
        theevilofthedaleks.title = ""
        theevilofthedaleks.broadcast = ""
        theevilofthedaleks.companions = ""
        theevilofthedaleks.director = ""
        theevilofthedaleks.doctor = ""
        theevilofthedaleks.length = ""
        theevilofthedaleks.producer = ""
        //Classic Series 5
        let thetombofthecybermen = TheTombOfTheCybermenClass(context: viewContext)
        thetombofthecybermen.title = ""
        thetombofthecybermen.broadcast = ""
        thetombofthecybermen.companions = ""
        thetombofthecybermen.director = ""
        thetombofthecybermen.doctor = ""
        thetombofthecybermen.length = ""
        thetombofthecybermen.producer = ""
        let theabominablesnowmen = TheAbominableSnowmenClass(context: viewContext)
        theabominablesnowmen.title = ""
        theabominablesnowmen.broadcast = ""
        theabominablesnowmen.companions = ""
        theabominablesnowmen.director = ""
        theabominablesnowmen.doctor = ""
        theabominablesnowmen.length = ""
        theabominablesnowmen.producer = ""
        let theicewarriors = TheIceWarriorsClass(context: viewContext)
        theicewarriors.title = ""
        theicewarriors.broadcast = ""
        theicewarriors.companions = ""
        theicewarriors.director = ""
        theicewarriors.doctor = ""
        theicewarriors.length = ""
        theicewarriors.producer = ""
        let theenemyoftheworld = TheEnemyOfTheWorldClass(context: viewContext)
        theenemyoftheworld.title = ""
        theenemyoftheworld.broadcast = ""
        theenemyoftheworld.companions = ""
        theenemyoftheworld.director = ""
        theenemyoftheworld.doctor = ""
        theenemyoftheworld.length = ""
        theenemyoftheworld.producer = ""
        let theweboffear = TheWebOfFearClass(context: viewContext)
        theweboffear.title = ""
        theweboffear.broadcast = ""
        theweboffear.companions = ""
        theweboffear.director = ""
        theweboffear.doctor = ""
        theweboffear.length = ""
        theweboffear.producer = ""
        let furyfromthedeep = FuryFromTheDeepClass(context: viewContext)
        furyfromthedeep.title = ""
        furyfromthedeep.broadcast = ""
        furyfromthedeep.companions = ""
        furyfromthedeep.director = ""
        furyfromthedeep.doctor = ""
        furyfromthedeep.length = ""
        furyfromthedeep.producer = ""
        let thewheelinspace = TheWheelInSpaceClass(context: viewContext)
        thewheelinspace.title = ""
        thewheelinspace.broadcast = ""
        thewheelinspace.companions = ""
        thewheelinspace.director = ""
        thewheelinspace.doctor = ""
        thewheelinspace.length = ""
        thewheelinspace.producer = ""
        //Classic Series 6
        let thedominators = TheDominatorsClass(context: viewContext)
        thedominators.title = ""
        thedominators.broadcast = ""
        thedominators.companions = ""
        thedominators.director = ""
        thedominators.doctor = ""
        thedominators.length = ""
        thedominators.producer = ""
        let themindrobber = TheMindRobberClass(context: viewContext)
        themindrobber.title = ""
        themindrobber.broadcast = ""
        themindrobber.companions = ""
        themindrobber.director = ""
        themindrobber.doctor = ""
        themindrobber.length = ""
        themindrobber.producer = ""
        let theinvasion = TheInvasionClass(context: viewContext)
        theinvasion.title = ""
        theinvasion.broadcast = ""
        theinvasion.companions = ""
        theinvasion.director = ""
        theinvasion.doctor = ""
        theinvasion.length = ""
        theinvasion.producer = ""
        let thekrotons = TheKrotonsClass(context: viewContext)
        thekrotons.title = ""
        thekrotons.broadcast = ""
        thekrotons.companions = ""
        thekrotons.director = ""
        thekrotons.doctor = ""
        thekrotons.length = ""
        thekrotons.producer = ""
        let theseedsofdeath = TheSeedsOfDeathClass(context: viewContext)
        theseedsofdeath.title = ""
        theseedsofdeath.broadcast = ""
        theseedsofdeath.companions = ""
        theseedsofdeath.director = ""
        theseedsofdeath.doctor = ""
        theseedsofdeath.length = ""
        theseedsofdeath.producer = ""
        let thespacepirates = TheSpacePiratesClass(context: viewContext)
        thespacepirates.title = ""
        thespacepirates.broadcast = ""
        thespacepirates.companions = ""
        thespacepirates.director = ""
        thespacepirates.doctor = ""
        thespacepirates.length = ""
        thespacepirates.producer = ""
        let thewargames = TheWarGamesClass(context: viewContext)
        thewargames.title = ""
        thewargames.broadcast = ""
        thewargames.companions = ""
        thewargames.director = ""
        thewargames.doctor = ""
        thewargames.length = ""
        thewargames.producer = ""
        //Classic Series 7
        let spearheadfromspace = SpearheadFromSpaceClass(context: viewContext)
        spearheadfromspace.title = ""
        spearheadfromspace.broadcast = ""
        spearheadfromspace.companions = ""
        spearheadfromspace.director = ""
        spearheadfromspace.doctor = ""
        spearheadfromspace.length = ""
        spearheadfromspace.producer = ""
        let andthesilurians = AndTheSiluriansClass(context: viewContext)
        andthesilurians.title = ""
        andthesilurians.broadcast = ""
        andthesilurians.companions = ""
        andthesilurians.director = ""
        andthesilurians.doctor = ""
        andthesilurians.length = ""
        andthesilurians.producer = ""
        let theambassadorsofdeath = TheAmbassadorsOfDeathClass(context: viewContext)
        theambassadorsofdeath.title = ""
        theambassadorsofdeath.broadcast = ""
        theambassadorsofdeath.companions = ""
        theambassadorsofdeath.director = ""
        theambassadorsofdeath.doctor = ""
        theambassadorsofdeath.length = ""
        theambassadorsofdeath.producer = ""
        let inferno = InfernoClass(context: viewContext)
        inferno.title = ""
        inferno.broadcast = ""
        inferno.companions = ""
        inferno.director = ""
        inferno.doctor = ""
        inferno.length = ""
        inferno.producer = ""
        //Classic Series 8
        let terroroftheautons = TerrorOfTheAutonsClass(context: viewContext)
        terroroftheautons.title = ""
        terroroftheautons.broadcast = ""
        terroroftheautons.companions = ""
        terroroftheautons.director = ""
        terroroftheautons.doctor = ""
        terroroftheautons.length = ""
        terroroftheautons.producer = ""
        let themindofevil = TheMindOfEvilClass(context: viewContext)
        themindofevil.title = ""
        themindofevil.broadcast = ""
        themindofevil.companions = ""
        themindofevil.director = ""
        themindofevil.doctor = ""
        themindofevil.length = ""
        themindofevil.producer = ""
        let theclawsofaxos = TheClawsOfAxosClass(context: viewContext)
        theclawsofaxos.title = ""
        theclawsofaxos.broadcast = ""
        theclawsofaxos.companions = ""
        theclawsofaxos.director = ""
        theclawsofaxos.doctor = ""
        theclawsofaxos.length = ""
        theclawsofaxos.producer = ""
        let colonyinspace = ColonyInSpaceClass(context: viewContext)
        colonyinspace.title = ""
        colonyinspace.broadcast = ""
        colonyinspace.companions = ""
        colonyinspace.director = ""
        colonyinspace.doctor = ""
        colonyinspace.length = ""
        colonyinspace.producer = ""
        let thedaemons = TheDaemonsClass(context: viewContext)
        thedaemons.title = ""
        thedaemons.broadcast = ""
        thedaemons.companions = ""
        thedaemons.director = ""
        thedaemons.doctor = ""
        thedaemons.length = ""
        thedaemons.producer = ""
        //Classic Series 9
        let dayofthedaleks = DayOfTheDaleksClass(context: viewContext)
        dayofthedaleks.title = ""
        dayofthedaleks.broadcast = ""
        dayofthedaleks.companions = ""
        dayofthedaleks.director = ""
        dayofthedaleks.doctor = ""
        dayofthedaleks.length = ""
        dayofthedaleks.producer = ""
        let thecurseofpeladon = TheCurseOfPeladonClass(context: viewContext)
        thecurseofpeladon.title = ""
        thecurseofpeladon.broadcast = ""
        thecurseofpeladon.companions = ""
        thecurseofpeladon.director = ""
        thecurseofpeladon.doctor = ""
        thecurseofpeladon.length = ""
        thecurseofpeladon.producer = ""
        let theseadevils = TheSeaDevilsClass(context: viewContext)
        theseadevils.title = ""
        theseadevils.broadcast = ""
        theseadevils.companions = ""
        theseadevils.director = ""
        theseadevils.doctor = ""
        theseadevils.length = ""
        theseadevils.producer = ""
        let themutants = TheMutantsClass(context: viewContext)
        themutants.title = ""
        themutants.broadcast = ""
        themutants.companions = ""
        themutants.director = ""
        themutants.doctor = ""
        themutants.length = ""
        themutants.producer = ""
        let thetimemonster = TheTimeMonsterClass(context: viewContext)
        thetimemonster.title = ""
        thetimemonster.broadcast = ""
        thetimemonster.companions = ""
        thetimemonster.director = ""
        thetimemonster.doctor = ""
        thetimemonster.length = ""
        thetimemonster.producer = ""
        //Classic Series 10
        let thethreedoctors = TheThreeDoctorsClass(context: viewContext)
        thethreedoctors.title = ""
        thethreedoctors.broadcast = ""
        thethreedoctors.companions = ""
        thethreedoctors.director = ""
        thethreedoctors.doctor = ""
        thethreedoctors.length = ""
        thethreedoctors.producer = ""
        let carnivalofmonsters = CarnivalOfMonstersClass(context: viewContext)
        carnivalofmonsters.title = ""
        carnivalofmonsters.broadcast = ""
        carnivalofmonsters.companions = ""
        carnivalofmonsters.director = ""
        carnivalofmonsters.doctor = ""
        carnivalofmonsters.length = ""
        carnivalofmonsters.producer = ""
        let frontierinspace = FrontierInSpaceClass(context: viewContext)
        frontierinspace.title = ""
        frontierinspace.broadcast = ""
        frontierinspace.companions = ""
        frontierinspace.director = ""
        frontierinspace.doctor = ""
        frontierinspace.length = ""
        frontierinspace.producer = ""
        let planetofthedaleks = PlanetOfTheDaleksClass(context: viewContext)
        planetofthedaleks.title = ""
        planetofthedaleks.broadcast = ""
        planetofthedaleks.companions = ""
        planetofthedaleks.director = ""
        planetofthedaleks.doctor = ""
        planetofthedaleks.length = ""
        planetofthedaleks.producer = ""
        let thegreendeath = TheGreenDeathClass(context: viewContext)
        thegreendeath.title = ""
        thegreendeath.broadcast = ""
        thegreendeath.companions = ""
        thegreendeath.director = ""
        thegreendeath.doctor = ""
        thegreendeath.length = ""
        thegreendeath.producer = ""
        //Classic Series 11
        let thetimewarrior = TheTimeWarriorClass(context: viewContext)
        thetimewarrior.title = ""
        thetimewarrior.broadcast = ""
        thetimewarrior.companions = ""
        thetimewarrior.director = ""
        thetimewarrior.doctor = ""
        thetimewarrior.length = ""
        thetimewarrior.producer = ""
        let invasionofthedinosaurs = InvasionOfTheDinosaursClass(context: viewContext)
        invasionofthedinosaurs.title = ""
        invasionofthedinosaurs.broadcast = ""
        invasionofthedinosaurs.companions = ""
        invasionofthedinosaurs.director = ""
        invasionofthedinosaurs.doctor = ""
        invasionofthedinosaurs.length = ""
        invasionofthedinosaurs.producer = ""
        let deathtothedaleks = DeathToTheDaleksClass(context: viewContext)
        deathtothedaleks.title = ""
        deathtothedaleks.broadcast = ""
        deathtothedaleks.companions = ""
        deathtothedaleks.director = ""
        deathtothedaleks.doctor = ""
        deathtothedaleks.length = ""
        deathtothedaleks.producer = ""
        let themonsterofpeladon = TheMonsterOfPeladonClass(context: viewContext)
        themonsterofpeladon.title = ""
        themonsterofpeladon.broadcast = ""
        themonsterofpeladon.companions = ""
        themonsterofpeladon.director = ""
        themonsterofpeladon.doctor = ""
        themonsterofpeladon.length = ""
        themonsterofpeladon.producer = ""
        let planetofthespiders = PlanetOfTheSpidersClass(context: viewContext)
        planetofthespiders.title = ""
        planetofthespiders.broadcast = ""
        planetofthespiders.companions = ""
        planetofthespiders.director = ""
        planetofthespiders.doctor = ""
        planetofthespiders.length = ""
        planetofthespiders.producer = ""
        //Classic Series 12
        let robot = RobotClass(context: viewContext)
        robot.title = ""
        robot.broadcast = ""
        robot.companions = ""
        robot.director = ""
        robot.doctor = ""
        robot.length = ""
        robot.producer = ""
        let thearkinspace = TheArkInSpaceClass(context: viewContext)
        thearkinspace.title = ""
        thearkinspace.broadcast = ""
        thearkinspace.companions = ""
        thearkinspace.director = ""
        thearkinspace.doctor = ""
        thearkinspace.length = ""
        thearkinspace.producer = ""
        let thesontaranexperiment = TheSontaranExperimentClass(context: viewContext)
        thesontaranexperiment.title = ""
        thesontaranexperiment.broadcast = ""
        thesontaranexperiment.companions = ""
        thesontaranexperiment.director = ""
        thesontaranexperiment.doctor = ""
        thesontaranexperiment.length = ""
        thesontaranexperiment.producer = ""
        let genesisofthedaleks = GenesisOfTheDaleksClass(context: viewContext)
        genesisofthedaleks.title = ""
        genesisofthedaleks.broadcast = ""
        genesisofthedaleks.companions = ""
        genesisofthedaleks.director = ""
        genesisofthedaleks.doctor = ""
        genesisofthedaleks.length = ""
        genesisofthedaleks.producer = ""
        let revengeofthecybermen = RevengeOfTheCybermenClass(context: viewContext)
        revengeofthecybermen.title = ""
        revengeofthecybermen.broadcast = ""
        revengeofthecybermen.companions = ""
        revengeofthecybermen.director = ""
        revengeofthecybermen.doctor = ""
        revengeofthecybermen.length = ""
        revengeofthecybermen.producer = ""
        //Classic Series 13
        let terrorofthezygons = TerrorOfTheZygonsClass(context: viewContext)
        terrorofthezygons.title = ""
        terrorofthezygons.broadcast = ""
        terrorofthezygons.companions = ""
        terrorofthezygons.director = ""
        terrorofthezygons.doctor = ""
        terrorofthezygons.length = ""
        terrorofthezygons.producer = ""
        let planetofevil = PlanetOfEvilClass(context: viewContext)
        planetofevil.title = ""
        planetofevil.broadcast = ""
        planetofevil.companions = ""
        planetofevil.director = ""
        planetofevil.doctor = ""
        planetofevil.length = ""
        planetofevil.producer = ""
        let pyramidsofmars = PyramidsOfMarsClass(context: viewContext)
        pyramidsofmars.title = ""
        pyramidsofmars.broadcast = ""
        pyramidsofmars.companions = ""
        pyramidsofmars.director = ""
        pyramidsofmars.doctor = ""
        pyramidsofmars.length = ""
        pyramidsofmars.producer = ""
        let theandroidinvasion = TheAndroidInvasionClass(context: viewContext)
        theandroidinvasion.title = ""
        theandroidinvasion.broadcast = ""
        theandroidinvasion.companions = ""
        theandroidinvasion.director = ""
        theandroidinvasion.doctor = ""
        theandroidinvasion.length = ""
        theandroidinvasion.producer = ""
        let thebrainofmorbius = TheBrainOfMorbiusClass(context: viewContext)
        thebrainofmorbius.title = ""
        thebrainofmorbius.broadcast = ""
        thebrainofmorbius.companions = ""
        thebrainofmorbius.director = ""
        thebrainofmorbius.doctor = ""
        thebrainofmorbius.length = ""
        thebrainofmorbius.producer = ""
        let theseedsofdoom = TheSeedsOfDoomClass(context: viewContext)
        theseedsofdoom.title = ""
        theseedsofdoom.broadcast = ""
        theseedsofdoom.companions = ""
        theseedsofdoom.director = ""
        theseedsofdoom.doctor = ""
        theseedsofdoom.length = ""
        theseedsofdoom.producer = ""
        //Classic Series 14
        let themasqueofmandragora = TheMasqueOfMandragoraClass(context: viewContext)
        themasqueofmandragora.title = ""
        themasqueofmandragora.broadcast = ""
        themasqueofmandragora.companions = ""
        themasqueofmandragora.director = ""
        themasqueofmandragora.doctor = ""
        themasqueofmandragora.length = ""
        themasqueofmandragora.producer = ""
        let thehandoffear = TheHandOfFearClass(context: viewContext)
        thehandoffear.title = ""
        thehandoffear.broadcast = ""
        thehandoffear.companions = ""
        thehandoffear.director = ""
        thehandoffear.doctor = ""
        thehandoffear.length = ""
        thehandoffear.producer = ""
        let thedeadlyassassin = TheDeadlyAssassinClass(context: viewContext)
        thedeadlyassassin.title = ""
        thedeadlyassassin.broadcast = ""
        thedeadlyassassin.companions = ""
        thedeadlyassassin.director = ""
        thedeadlyassassin.doctor = ""
        thedeadlyassassin.length = ""
        thedeadlyassassin.producer = ""
        let thefaceofevil = TheFaceOfEvilClass(context: viewContext)
        thefaceofevil.title = ""
        thefaceofevil.broadcast = ""
        thefaceofevil.companions = ""
        thefaceofevil.director = ""
        thefaceofevil.doctor = ""
        thefaceofevil.length = ""
        thefaceofevil.producer = ""
        let therobotsofdeath = TheRobotsOfDeathClass(context: viewContext)
        therobotsofdeath.title = ""
        therobotsofdeath.broadcast = ""
        therobotsofdeath.companions = ""
        therobotsofdeath.director = ""
        therobotsofdeath.doctor = ""
        therobotsofdeath.length = ""
        therobotsofdeath.producer = ""
        let thetalonsofwengchiang = TheTalonsOfWengChiangClass(context: viewContext)
        therobotsofdeath.title = ""
        therobotsofdeath.broadcast = ""
        therobotsofdeath.companions = ""
        therobotsofdeath.director = ""
        therobotsofdeath.doctor = ""
        therobotsofdeath.length = ""
        therobotsofdeath.producer = ""
        //Classic Series 15
        let horroroffangrock = HorrorOfFangRockClass(context: viewContext)
        horroroffangrock.title = ""
        horroroffangrock.broadcast = ""
        horroroffangrock.companions = ""
        horroroffangrock.director = ""
        horroroffangrock.doctor = ""
        horroroffangrock.length = ""
        horroroffangrock.producer = ""
        let theinvisibleenemy = TheInvisibleEnemyClass(context: viewContext)
        theinvisibleenemy.title = ""
        theinvisibleenemy.broadcast = ""
        theinvisibleenemy.companions = ""
        theinvisibleenemy.director = ""
        theinvisibleenemy.doctor = ""
        theinvisibleenemy.length = ""
        theinvisibleenemy.producer = ""
        let imageofthefendahl = ImageOfTheFendahlClass(context: viewContext)
        imageofthefendahl.title = ""
        imageofthefendahl.broadcast = ""
        imageofthefendahl.companions = ""
        imageofthefendahl.director = ""
        imageofthefendahl.doctor = ""
        imageofthefendahl.length = ""
        imageofthefendahl.producer = ""
        let thesunmakers = TheSunMakersClass(context: viewContext)
        thesunmakers.title = ""
        thesunmakers.broadcast = ""
        thesunmakers.companions = ""
        thesunmakers.director = ""
        thesunmakers.doctor = ""
        thesunmakers.length = ""
        thesunmakers.producer = ""
        let underworld = UnderworldClass(context: viewContext)
        underworld.title = ""
        underworld.broadcast = ""
        underworld.companions = ""
        underworld.director = ""
        underworld.doctor = ""
        underworld.length = ""
        underworld.producer = ""
        let theinvasionoftime = TheInvasionOfTimeClass(context: viewContext)
        theinvasionoftime.title = ""
        theinvasionoftime.broadcast = ""
        theinvasionoftime.companions = ""
        theinvasionoftime.director = ""
        theinvasionoftime.doctor = ""
        theinvasionoftime.length = ""
        theinvasionoftime.producer = ""
        //Classic Series 16
        let theribosoperation = TheRibosOperationClass(context: viewContext)
        theribosoperation.title = ""
        theribosoperation.broadcast = ""
        theribosoperation.companions = ""
        theribosoperation.director = ""
        theribosoperation.doctor = ""
        theribosoperation.length = ""
        theribosoperation.producer = ""
        let thepirateplanet = ThePiratePlanetClass(context: viewContext)
        thepirateplanet.title = ""
        thepirateplanet.broadcast = ""
        thepirateplanet.companions = ""
        thepirateplanet.director = ""
        thepirateplanet.doctor = ""
        thepirateplanet.length = ""
        thepirateplanet.producer = ""
        let thestonesofblood = TheStonesOfBloodClass(context: viewContext)
        thestonesofblood.title = ""
        thestonesofblood.broadcast = ""
        thestonesofblood.companions = ""
        thestonesofblood.director = ""
        thestonesofblood.doctor = ""
        thestonesofblood.length = ""
        thestonesofblood.producer = ""
        let theandroidsoftara = TheAndroidsOfTaraClass(context: viewContext)
        theandroidsoftara.title = ""
        theandroidsoftara.broadcast = ""
        theandroidsoftara.companions = ""
        theandroidsoftara.director = ""
        theandroidsoftara.doctor = ""
        theandroidsoftara.length = ""
        theandroidsoftara.producer = ""
        let thepowerofkroll = ThePowerOfKrollClass(context: viewContext)
        thepowerofkroll.title = ""
        thepowerofkroll.broadcast = ""
        thepowerofkroll.companions = ""
        thepowerofkroll.director = ""
        thepowerofkroll.doctor = ""
        thepowerofkroll.length = ""
        thepowerofkroll.producer = ""
        let thearmageddonfactor = TheArmageddonFactorClass(context: viewContext)
        thearmageddonfactor.title = ""
        thearmageddonfactor.broadcast = ""
        thearmageddonfactor.companions = ""
        thearmageddonfactor.director = ""
        thearmageddonfactor.doctor = ""
        thearmageddonfactor.length = ""
        thearmageddonfactor.producer = ""
        //Classic Series 17
        let destinyofthedaleks = DestinyOfTheDaleksClass(context: viewContext)
        destinyofthedaleks.title = ""
        destinyofthedaleks.broadcast = ""
        destinyofthedaleks.companions = ""
        destinyofthedaleks.director = ""
        destinyofthedaleks.doctor = ""
        destinyofthedaleks.length = ""
        destinyofthedaleks.producer = ""
        let cityofdeath = CityOfDeathClass(context: viewContext)
        cityofdeath.title = ""
        cityofdeath.broadcast = ""
        cityofdeath.companions = ""
        cityofdeath.director = ""
        cityofdeath.doctor = ""
        cityofdeath.length = ""
        cityofdeath.producer = ""
        let thecreaturefromthepit = TheCreatureFromThePitClass(context: viewContext)
        thecreaturefromthepit.title = ""
        thecreaturefromthepit.broadcast = ""
        thecreaturefromthepit.companions = ""
        thecreaturefromthepit.director = ""
        thecreaturefromthepit.doctor = ""
        thecreaturefromthepit.length = ""
        thecreaturefromthepit.producer = ""
        let nightmareofeden = NightmareOfEdenClass(context: viewContext)
        nightmareofeden.title = ""
        nightmareofeden.broadcast = ""
        nightmareofeden.companions = ""
        nightmareofeden.director = ""
        nightmareofeden.doctor = ""
        nightmareofeden.length = ""
        nightmareofeden.producer = ""
        let thehornsofnimon = TheHornsOfNimonClass(context: viewContext)
        thehornsofnimon.title = ""
        thehornsofnimon.broadcast = ""
        thehornsofnimon.companions = ""
        thehornsofnimon.director = ""
        thehornsofnimon.doctor = ""
        thehornsofnimon.length = ""
        thehornsofnimon.producer = ""
        let shada = ShadaClass(context: viewContext)
        shada.title = ""
        shada.broadcast = ""
        shada.companions = ""
        shada.director = ""
        shada.doctor = ""
        shada.length = ""
        shada.producer = ""
        //Classic Series 18
        let theleisurehive = TheLeisureHiveClass(context: viewContext)
        theleisurehive.title = ""
        theleisurehive.broadcast = ""
        theleisurehive.companions = ""
        theleisurehive.director = ""
        theleisurehive.doctor = ""
        theleisurehive.length = ""
        theleisurehive.producer = ""
        let meglos = MeglosClass(context: viewContext)
        meglos.title = ""
        meglos.broadcast = ""
        meglos.companions = ""
        meglos.director = ""
        meglos.doctor = ""
        meglos.length = ""
        meglos.producer = ""
        let fullcircle = FullCircleClass(context: viewContext)
        fullcircle.title = ""
        fullcircle.broadcast = ""
        fullcircle.companions = ""
        fullcircle.director = ""
        fullcircle.doctor = ""
        fullcircle.length = ""
        fullcircle.producer = ""
        let stateofdecay = StateOfDecayClass(context: viewContext)
        stateofdecay.title = ""
        stateofdecay.broadcast = ""
        stateofdecay.companions = ""
        stateofdecay.director = ""
        stateofdecay.doctor = ""
        stateofdecay.length = ""
        stateofdecay.producer = ""
        let warriorsgate = WarriorsGateClass(context: viewContext)
        warriorsgate.title = ""
        warriorsgate.broadcast = ""
        warriorsgate.companions = ""
        warriorsgate.director = ""
        warriorsgate.doctor = ""
        warriorsgate.length = ""
        warriorsgate.producer = ""
        let thekeeperoftraken = TheKeeperOfTrakenClass(context: viewContext)
        thekeeperoftraken.title = ""
        thekeeperoftraken.broadcast = ""
        thekeeperoftraken.companions = ""
        thekeeperoftraken.director = ""
        thekeeperoftraken.doctor = ""
        thekeeperoftraken.length = ""
        thekeeperoftraken.producer = ""
        let logopolis = LogopolisClass(context: viewContext)
        logopolis.title = ""
        logopolis.broadcast = ""
        logopolis.companions = ""
        logopolis.director = ""
        logopolis.doctor = ""
        logopolis.length = ""
        logopolis.producer = ""
        //Classic Series 19
        let castrovalva = CastrovalvaClass(context: viewContext)
        castrovalva.title = ""
        castrovalva.broadcast = ""
        castrovalva.companions = ""
        castrovalva.director = ""
        castrovalva.doctor = ""
        castrovalva.length = ""
        castrovalva.producer = ""
        let fourtodoomsday = FourToDoomsdayClass(context: viewContext)
        fourtodoomsday.title = ""
        fourtodoomsday.broadcast = ""
        fourtodoomsday.companions = ""
        fourtodoomsday.director = ""
        fourtodoomsday.doctor = ""
        fourtodoomsday.length = ""
        fourtodoomsday.producer = ""
        let kinda = KindaClass(context: viewContext)
        kinda.title = ""
        kinda.broadcast = ""
        kinda.companions = ""
        kinda.director = ""
        kinda.doctor = ""
        kinda.length = ""
        kinda.producer = ""
        let thevisitation = TheVisitationClass(context: viewContext)
        thevisitation.title = ""
        thevisitation.broadcast = ""
        thevisitation.companions = ""
        thevisitation.director = ""
        thevisitation.doctor = ""
        thevisitation.length = ""
        thevisitation.producer = ""
        let blackorchid = BlackOrchidClass(context: viewContext)
        blackorchid.title = ""
        blackorchid.broadcast = ""
        blackorchid.companions = ""
        blackorchid.director = ""
        blackorchid.doctor = ""
        blackorchid.length = ""
        blackorchid.producer = ""
        let earthshock = EarthshockClass(context: viewContext)
        earthshock.title = ""
        earthshock.broadcast = ""
        earthshock.companions = ""
        earthshock.director = ""
        earthshock.doctor = ""
        earthshock.length = ""
        earthshock.producer = ""
        let timeflight = TimeFlightClass(context: viewContext)
        timeflight.title = ""
        timeflight.broadcast = ""
        timeflight.companions = ""
        timeflight.director = ""
        timeflight.doctor = ""
        timeflight.length = ""
        timeflight.producer = ""
        //Classic Series 20
        let arcofinfinity = ArcOfInfinityClass(context: viewContext)
        arcofinfinity.title = ""
        arcofinfinity.broadcast = ""
        arcofinfinity.companions = ""
        arcofinfinity.director = ""
        arcofinfinity.doctor = ""
        arcofinfinity.length = ""
        arcofinfinity.producer = ""
        let snakedance = SnakedanceClass(context: viewContext)
        snakedance.title = ""
        snakedance.broadcast = ""
        snakedance.companions = ""
        snakedance.director = ""
        snakedance.doctor = ""
        snakedance.length = ""
        snakedance.producer = ""
        let mawdrynundead = MawdrynUndeadClass(context: viewContext)
        mawdrynundead.title = ""
        mawdrynundead.broadcast = ""
        mawdrynundead.companions = ""
        mawdrynundead.director = ""
        mawdrynundead.doctor = ""
        mawdrynundead.length = ""
        mawdrynundead.producer = ""
        let terminus = TerminusClass(context: viewContext)
        terminus.title = ""
        terminus.broadcast = ""
        terminus.companions = ""
        terminus.director = ""
        terminus.doctor = ""
        terminus.length = ""
        terminus.producer = ""
        let enlightenment = EnlightenmentClass(context: viewContext)
        enlightenment.title = ""
        enlightenment.broadcast = ""
        enlightenment.companions = ""
        enlightenment.director = ""
        enlightenment.doctor = ""
        enlightenment.length = ""
        enlightenment.producer = ""
        let thekingsdemons = TheKingsDemonsClass(context: viewContext)
        thekingsdemons.title = ""
        thekingsdemons.broadcast = ""
        thekingsdemons.companions = ""
        thekingsdemons.director = ""
        thekingsdemons.doctor = ""
        thekingsdemons.length = ""
        thekingsdemons.producer = ""
        let thefivedoctors = TheFiveDoctorsClass(context: viewContext)
        thefivedoctors.title = ""
        thefivedoctors.broadcast = ""
        thefivedoctors.companions = ""
        thefivedoctors.director = ""
        thefivedoctors.doctor = ""
        thefivedoctors.length = ""
        thefivedoctors.producer = ""
        //Classic Series 21
        let warriorsofthedeep = WarriorsOfTheDeepClass(context: viewContext)
        warriorsofthedeep.title = ""
        warriorsofthedeep.broadcast = ""
        warriorsofthedeep.companions = ""
        warriorsofthedeep.director = ""
        warriorsofthedeep.doctor = ""
        warriorsofthedeep.length = ""
        warriorsofthedeep.producer = ""
        let theawakening = TheAwakeningClass(context: viewContext)
        theawakening.title = ""
        theawakening.broadcast = ""
        theawakening.companions = ""
        theawakening.director = ""
        theawakening.doctor = ""
        theawakening.length = ""
        theawakening.producer = ""
        let frontios = FrontiosClass(context: viewContext)
        frontios.title = ""
        frontios.broadcast = ""
        frontios.companions = ""
        frontios.director = ""
        frontios.doctor = ""
        frontios.length = ""
        frontios.producer = ""
        let resurrectionofthedaleks = ResurrectionOfTheDaleksClass(context: viewContext)
        resurrectionofthedaleks.title = ""
        resurrectionofthedaleks.broadcast = ""
        resurrectionofthedaleks.companions = ""
        resurrectionofthedaleks.director = ""
        resurrectionofthedaleks.doctor = ""
        resurrectionofthedaleks.length = ""
        resurrectionofthedaleks.producer = ""
        let planetoffire = PlanetOfFireClass(context: viewContext)
        planetoffire.title = ""
        planetoffire.broadcast = ""
        planetoffire.companions = ""
        planetoffire.director = ""
        planetoffire.doctor = ""
        planetoffire.length = ""
        planetoffire.producer = ""
        let thecavesofandrozani = TheCavesOfAndrozaniClass(context: viewContext)
        thecavesofandrozani.title = ""
        thecavesofandrozani.broadcast = ""
        thecavesofandrozani.companions = ""
        thecavesofandrozani.director = ""
        thecavesofandrozani.doctor = ""
        thecavesofandrozani.length = ""
        thecavesofandrozani.producer = ""
        let thetwindilemma = TheTwinDilemmaClass(context: viewContext)
        thetwindilemma.title = ""
        thetwindilemma.broadcast = ""
        thetwindilemma.companions = ""
        thetwindilemma.director = ""
        thetwindilemma.doctor = ""
        thetwindilemma.length = ""
        thetwindilemma.producer = ""
        //Classic Series 22
        let attackofthecybermen = AttackOfTheCybermenClass(context: viewContext)
        attackofthecybermen.title = ""
        attackofthecybermen.broadcast = ""
        attackofthecybermen.companions = ""
        attackofthecybermen.director = ""
        attackofthecybermen.doctor = ""
        attackofthecybermen.length = ""
        attackofthecybermen.producer = ""
        let vengeanceonvaros = VengeanceOnVarosClass(context: viewContext)
        vengeanceonvaros.title = ""
        vengeanceonvaros.broadcast = ""
        vengeanceonvaros.companions = ""
        vengeanceonvaros.director = ""
        vengeanceonvaros.doctor = ""
        vengeanceonvaros.length = ""
        vengeanceonvaros.producer = ""
        let themarkoftherani = TheMarkOfTheRaniClass(context: viewContext)
        themarkoftherani.title = ""
        themarkoftherani.broadcast = ""
        themarkoftherani.companions = ""
        themarkoftherani.director = ""
        themarkoftherani.doctor = ""
        themarkoftherani.length = ""
        themarkoftherani.producer = ""
        let thetwodoctors = TheTwoDoctorsClass(context: viewContext)
        thetwodoctors.title = ""
        thetwodoctors.broadcast = ""
        thetwodoctors.companions = ""
        thetwodoctors.director = ""
        thetwodoctors.doctor = ""
        thetwodoctors.length = ""
        thetwodoctors.producer = ""
        let timelash = TimelashClass(context: viewContext)
        timelash.title = ""
        timelash.broadcast = ""
        timelash.companions = ""
        timelash.director = ""
        timelash.doctor = ""
        timelash.length = ""
        timelash.producer = ""
        let revelationofthedaleks = RevelationOfTheDaleksClass(context: viewContext)
        revelationofthedaleks.title = ""
        revelationofthedaleks.broadcast = ""
        revelationofthedaleks.companions = ""
        revelationofthedaleks.director = ""
        revelationofthedaleks.doctor = ""
        revelationofthedaleks.length = ""
        revelationofthedaleks.producer = ""
        //Classic Series 23
        let themysteriousplanet = TheMysteriousPlanetClass(context: viewContext)
        themysteriousplanet.title = ""
        themysteriousplanet.broadcast = ""
        themysteriousplanet.companions = ""
        themysteriousplanet.director = ""
        themysteriousplanet.doctor = ""
        themysteriousplanet.length = ""
        themysteriousplanet.producer = ""
        let mindwarp = MindwarpClass(context: viewContext)
        mindwarp.title = ""
        mindwarp.broadcast = ""
        mindwarp.companions = ""
        mindwarp.director = ""
        mindwarp.doctor = ""
        mindwarp.length = ""
        mindwarp.producer = ""
        let terrorofthevervoids = TerrorOfTheVervoidsClass(context: viewContext)
        terrorofthevervoids.title = ""
        terrorofthevervoids.broadcast = ""
        terrorofthevervoids.companions = ""
        terrorofthevervoids.director = ""
        terrorofthevervoids.doctor = ""
        terrorofthevervoids.length = ""
        terrorofthevervoids.producer = ""
        let theultimatefoe = TheUltimateFoeClass(context: viewContext)
        theultimatefoe.title = ""
        theultimatefoe.broadcast = ""
        theultimatefoe.companions = ""
        theultimatefoe.director = ""
        theultimatefoe.doctor = ""
        theultimatefoe.length = ""
        theultimatefoe.producer = ""
        //Classic Series 24
        let timeandtherani = TimeAndTheRaniClass(context: viewContext)
        timeandtherani.title = ""
        timeandtherani.broadcast = ""
        timeandtherani.companions = ""
        timeandtherani.director = ""
        timeandtherani.doctor = ""
        timeandtherani.length = ""
        timeandtherani.producer = ""
        let paradisetowers = ParadiseTowersClass(context: viewContext)
        paradisetowers.title = ""
        paradisetowers.broadcast = ""
        paradisetowers.companions = ""
        paradisetowers.director = ""
        paradisetowers.doctor = ""
        paradisetowers.length = ""
        paradisetowers.producer = ""
        let deltaandthebannermen = DeltaAndTheBannermenClass(context: viewContext)
        deltaandthebannermen.title = ""
        deltaandthebannermen.broadcast = ""
        deltaandthebannermen.companions = ""
        deltaandthebannermen.director = ""
        deltaandthebannermen.doctor = ""
        deltaandthebannermen.length = ""
        deltaandthebannermen.producer = ""
        let dragonfire = DragonfireClass(context: viewContext)
        dragonfire.title = ""
        dragonfire.broadcast = ""
        dragonfire.companions = ""
        dragonfire.director = ""
        dragonfire.doctor = ""
        dragonfire.length = ""
        dragonfire.producer = ""
        //Classic Series 25
        let remembranceofthedaleks = RememranceOfTheDaleksClass(context: viewContext)
        remembranceofthedaleks.title = ""
        remembranceofthedaleks.broadcast = ""
        remembranceofthedaleks.companions = ""
        remembranceofthedaleks.director = ""
        remembranceofthedaleks.doctor = ""
        remembranceofthedaleks.length = ""
        remembranceofthedaleks.producer = ""
        let thehappinesspatrol = TheHappinessPatrolClass(context: viewContext)
        thehappinesspatrol.title = ""
        thehappinesspatrol.broadcast = ""
        thehappinesspatrol.companions = ""
        thehappinesspatrol.director = ""
        thehappinesspatrol.doctor = ""
        thehappinesspatrol.length = ""
        thehappinesspatrol.producer = ""
        let silvernemesis = SilverNemesisClass(context: viewContext)
        silvernemesis.title = ""
        silvernemesis.broadcast = ""
        silvernemesis.companions = ""
        silvernemesis.director = ""
        silvernemesis.doctor = ""
        silvernemesis.length = ""
        silvernemesis.producer = ""
        let thegreatestshowinthegalaxy = TheGreatestShowInTheGalaxyClass(context: viewContext)
        thegreatestshowinthegalaxy.title = ""
        thegreatestshowinthegalaxy.broadcast = ""
        thegreatestshowinthegalaxy.companions = ""
        thegreatestshowinthegalaxy.director = ""
        thegreatestshowinthegalaxy.doctor = ""
        thegreatestshowinthegalaxy.length = ""
        thegreatestshowinthegalaxy.producer = ""
        //Classic Series 26
        let battlefield = BattlefieldClass(context: viewContext)
        battlefield.title = ""
        battlefield.broadcast = ""
        battlefield.companions = ""
        battlefield.director = ""
        battlefield.doctor = ""
        battlefield.length = ""
        battlefield.producer = ""
        let ghostlight = GhostLightClass(context: viewContext)
        ghostlight.title = ""
        ghostlight.broadcast = ""
        ghostlight.companions = ""
        ghostlight.director = ""
        ghostlight.doctor = ""
        ghostlight.length = ""
        ghostlight.producer = ""
        let thecurseoffenric = TheCurseOfFenricClass(context: viewContext)
        thecurseoffenric.title = ""
        thecurseoffenric.broadcast = ""
        thecurseoffenric.companions = ""
        thecurseoffenric.director = ""
        thecurseoffenric.doctor = ""
        thecurseoffenric.length = ""
        thecurseoffenric.producer = ""
        let survival = SurvivalClass(context: viewContext)
        survival.title = ""
        survival.broadcast = ""
        survival.companions = ""
        survival.director = ""
        survival.doctor = ""
        survival.length = ""
        survival.producer = ""
        let tvmovie = TVMovieClass(context: viewContext)
        tvmovie.title = ""
        tvmovie.broadcast = ""
        tvmovie.companions = ""
        tvmovie.director = ""
        tvmovie.doctor = ""
        tvmovie.length = ""
        tvmovie.producer = ""
        //New Series 1
        let rose = RoseClass(context: viewContext)
        let theednofthworld = TheEndOfTheWorldClass(context: viewContext)
        let theunquietdead = TheUnquietDeadClass(context: viewContext)
        let aliensoflondon = AliensOfLondonClass(context: viewContext)
        let worldwarthree = WorldWarThreeClass(context: viewContext)
        let dalek = DalekClass(context: viewContext)
        let thelonggame = TheLongGameClass(context: viewContext)
        let fathersday = FathersDay(context: viewContext)
        let theemptychild = TheEmptyChildClass(context: viewContext)
        let thedoctordances = TheDoctorDancesClass(context: viewContext)
        let boomtown = BoomTownClass(context: viewContext)
        let badwolf = BadWolfClass(context: viewContext)
        //New Series 2
        let thechristmasinvasion = TheChristmasInvasionClass(context: viewContext)
        let newearth = NewEarthClass(context: viewContext)
        let toothandclaw = ToothAndClawClass(context: viewContext)
        let schoolreunion = SchoolReunionClass(context: viewContext)
        let thegirlinthefireplace = TheGirlInTheFireplaceClass(context: viewContext)
        let riseofthecybermen = RiseOfTheCybermenClass(context: viewContext)
        let theageofsteel = TheAgeOfSteel(context: viewContext)
        let theidiotslantern = TheIdiotsLanternClass(context: viewContext)
        let theimpossibleplanet = TheImpossiblePlanetClass(context: viewContext)
        let thesatanpit = TheSatanPitClass(context: viewContext)
        let loveandmonsters = LoveAndMonstersClass(context: viewContext)
        let fearher = FearHerClass(context: viewContext)
        let armyofghosts = ArmyOfGhostsClass(context: viewContext)
        let doomsday = DoomsdayClass(context: viewContext)
        //New Series 3
        let therunawaybride = TheRunawayBrideClass(context: viewContext)
        let smithandjones = SmithAndJonesClass(context: viewContext)
        let gridlock = GridlockClass(context: viewContext)
        let daleksinmanhattan = DaleksInManhattanClass(context: viewContext)
        let evolutionofthedaleks = EvolutionOfTheDaleksClass(context: viewContext)
        let thelazarusexperiment = TheLazarusExperimentClass(context: viewContext)
        let fortytwo = FortyTwoClass(context: viewContext)
        let humannature = HumanNatureClass(context: viewContext)
        let thefamilyofblood = TheFamilyOfBloodClass(context: viewContext)
        let blink = BlinkClass(context: viewContext)
        let utopia = UtopiaClass(context: viewContext)
        let thesoundofdrums = TheSoundOfDrumsClass(context: viewContext)
        let lastofthetimelords = LastOfTheTimeLordsClass(context: viewContext)
        //New Series 4
        
        //New Series 5
        //New Series 6
        //New Series 7
        //New Series 8
        //New Series 9
        //New Series 10
        //New Series 11
        //New Series 12
        //New Series 13
        do {
            try viewContext.save()
        } catch {
            // Replace this implementation with code to handle the error appropriately.
            // fatalError() causes the application to generate a crash log and terminate. You should not use this function in a shipping application, although it may be useful during development.
            let nsError = error as NSError
            fatalError("Unresolved error \(nsError), \(nsError.userInfo)")
        }
        return result
    }()

    let container: NSPersistentContainer

    init(inMemory: Bool = false) {
        container = NSPersistentContainer(name: "Main")
        if inMemory {
            container.persistentStoreDescriptions.first!.url = URL(fileURLWithPath: "/dev/null")
        }
        container.loadPersistentStores(completionHandler: { (storeDescription, error) in
            if let error = error as NSError? {
                // Replace this implementation with code to handle the error appropriately.
                // fatalError() causes the application to generate a crash log and terminate. You should not use this function in a shipping application, although it may be useful during development.

                /*
                Typical reasons for an error here include:
                * The parent directory does not exist, cannot be created, or disallows writing.
                * The persistent store is not accessible, due to permissions or data protection when the device is locked.
                * The device is out of space.
                * The store could not be migrated to the current model version.
                Check the error message to determine what the actual problem was.
                */
                fatalError("Unresolved error \(error), \(error.userInfo)")
            }
        })
    }
    func save() {
        let context = container.viewContext

        if context.hasChanges {
            do {
                try context.save()
            } catch {
                // Show some error here
            }
        }
    }
}
